# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Anders Tankred Holm
logo:               # Logo image URL
description:        Working at LEGO something something
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://tankred.me' # The base hostname & protocol for your site
twitter:            https://twitter.com/atholm
facebook:           https://www.facebook.com/atholm/
instagram:          https://www.instagram.com/atholm

markdown:  kramdown
permalink: pretty
paginate:  9
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  anders:
    name:             Anders Tanrked Holm
    bio:              Playing with digital bricks at LEGO. I'm the host of http://filmsnak.dk and creator of http://pixeldb.net
    gravatar:         https://s.gravatar.com/avatar/c6f5d3892374ef5f416c8188f0462c8e?s=150
    email:            anders@atholm.com
    website:          https://tankred.me
    twitter_username: atholm