# Site settings
title: Anders Tankred Holm
description: "Playing with digital bricks at <a style='text-decoration:underline;' href='https://lego.com'>LEGO</a><br/>Host of <a style='text-decoration: underline;' href='https://filmsnak.dk'>Film Snak</a> and developer of <a style='text-decoration: underline;' href='https://itunes.apple.com/us/app/pixeldb-video-game-releases-videos-wiki/id1167943717?mt=8&at=1010luhA'>Pixeldb for iOS</a>"
url: 'http://tankred.me/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Anders Tankred Holm'
  email: anders@atholm.com
  twitter_username: atholm
  facebook_username: atholm
  linkedin_username:  atholm

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
