version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist jekyll-feed
  build:
    commands:
      - LANG=en_US.UTF-8
      - echo "******** Bundle Update ********"
      - bundle install
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://tankred.me